---
version: 2
project_name: cfop-generator
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
brews:
  - name: cfop-generator
    repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: https://containeroo.ch
    description: CLI tool to convert exported Cloudflare zones to cloudflare-operator DNSRecord objects
    license: GNU General Public License v3.0
    dependencies:
      - name: go
        type: optional
    install: |-
      bin.install "cfop-generator"
