---
version: 2
project_name: cfop-generator
before:
  hooks:
    - go mod tidy
builds:
  - id: cfop-generator
    main: ./main.go
    binary: cfop-generator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*
      - completions/*
checksum:
  name_template: checksums.txt
homebrew_casks:
  - name: cfop-generator
    repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://containeroo.ch
    description: CLI tool to convert exported Cloudflare zones to cloudflare-operator DNSRecord objects
    license: GPL-3.0-only
    binaries:
      - cfop-generator
    completions:
      bash: completions/cfop-generator.bash
      zsh: completions/cfop-generator.zsh
